= CodeStyle

        . Код на Python соотвествует стандартам PEP8, camelCase.
        . Для организации условных переходов используется оператор if-else.
        . В проекте соблюдаются принципы DRY и KISS.
        . Используемая БД - sqlite, используемая ORM - sqlmodel.
 
        . В рамках определения модели данных имена переменных, функций и классов информативны. Локальные переменные могут быть неинформативны.
        . В проекте применяется модульная структура.
        . SOLID не используется, т.к. не применяется ООП.
        . Использование внешних API и сервисов не предполагается.
 
        . Код бэкенда пишется на Python, поэтому код форматируется отступами и переносами строк в соответствии со стандартом PEP8. Код фронтенда пишется на JavaScript, поэтому код форматируется отступами и переносами строк, табуляцией в 4 пробела в соответствии с prettier.
        . Используются файлы конфигурации версий библиотек. Бэкенд: requirements.txt. Фронтенд: Packages.json.
        . Обновление и поддержка ПО после выпуска планируется.
 
        . Комментарии используются и оформляются с помощью символа '#'.
        . Проверка типов данных и корректности ввода данных осуществляется с помощью пакета pydantic.
        . Обработка входящих и исходящих запросов сервера осуществляется в асинхронном режиме.
        . Рефакторинг кода для улучшения его читаемости осуществляется каждые две недели.
 
        . Осуществляется разделение файловой структуры проекта на бэкенд и фронтенд. В рамках бэкенда осуществляется разделение на основную часть, включающую в себя инициализацию сервера, и на файлы, соотвествующие маршрутам API.
        . Планируется документирование API и интерфейсов в соответствии со стандартом Docstring.
        . Обработка ошибок осуществляется в виде возврата HTTP-исключений. Логирование ошибок производится внутренними средствами FastAPI.
 
        . Используется стандартная библиотека Python.
        . В рамках работы с библиотекой предполагается использование паттернов "Синглтон" и "Декоратор"
        . Для отслеживания изменений в проекте используется система контроля версий Git. Коммит должен представлять из себя изменения в рамках ОДНОГО модуля и иметь единичную ответственность, для отслеживания поломок. Pull request может содержать несколько коммитов, но все они должны реализовывать только одну фичу. Разработка проводится в личной ветке. Для удалённого хранения кода используется система удалённых репозиториев Github.

        . Не допускается уровень вложенности выше двух. Рекомендуемая длина функций - не более 20 строк.
        . Обеспечение безопасности кода не предполагается.
        . Используется контейнеризация в Docker, система оркестрации не используется.

        . Тестирование не производится.
        . Предполагается наличие английской и русской версий веб-приложения.
        . Разработка веб-приложения ведётся с помощью Material UI Kit.
        . Используется хэширование пароля пользователя по алгоритму sha256.
